version: '3.1'
services:
  api:
    build: ./
    depends_on:
      - pgdb
      - rabbitmq
    ports:
      - "8080:8080"
    restart: always

  pgdb:
    image: "postgres:latest"
    container_name: "pgdb"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=postgres
    ports:
      - "54320:5432"
    volumes:
      - /data/db/postgres:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - /data/rabbitmq:/var/lib/rabbitmq
